export const sourceList = [<></>, <><a href='https://eng.libretexts.org/Bookshelves/Electrical_Engineering/Signal_Processing_and_Modeling/Signals_and_Systems_(Baraniuk_et_al.)'>Signals and Systems</a> (Baraniuk et al.)</>,
    <><a href='https://www.ece.rice.edu/~dhj/courses/elec241/col10040.pdf'>Fundamentals of Electrical Engineering I</a> by Don H. Johnson</>,
    <><a href='https://en.wikibooks.org/wiki/Signals_and_Systems'>Signals and Systems</a> from Wikibooks</>,
    <>Random Wikipedia Articles</>,
    <><a href='https://openstax.org/details/books/college-physics-2e'>College Physics</a> from OpenStax</>,
    <><a href='https://openstax.org/details/books/university-physics-volume-2'>University Physics (Vol 2)</a> from OpenStax</>,
    <><a href='https://openstax.org/details/books/introductory-statistics-2e'>Introductory Statistics (2e)</a> from OpenStax</>,
    <>MIT 6.S191: <a href='http://introtodeeplearning.com/2023/index.html'>Introduction to Deep Learning</a>, &copy; Alexander Amini and Ava Soleimany</>,
    <><a href='https://d2l.ai'>d2l.ai</a> (Dive into Deep Learning)</>,
    <>Youtube playlist: <a href='https://www.youtube.com/playlist?list=PLbFrQnW0BNMUkAFj4MjYauXBPtO3I9O_k'>Billy Go's Beginner Korean Course</a></>,
    <>koreanwikiproject.com</>,
    <>Youtube Channel: <a href='https://www.youtube.com/@KOREANFULLCOURSE'>KOREAN FULL COURSE</a></>,
    <>90daykorean.com</>,
    <>howtostudykorean.com</>,
    <>Renshuu</>,
    <>Doulingo</>,
    <>http://www.lqtoronto.com/videos.html</>,
    <>Madinah Arabic Book 3 from <a href="http://www.lqtoronto.com/madinaarabic.html">lqtoronto</a></>,
    <><a href='https://people.cs.vt.edu/~shaffer/Book/'>Data Structures & Algorithm Analysis</a> by Clifford A. Shaffer (Java edition 3.2.0.10)</>,
    <><a href='https://opendsa-server.cs.vt.edu/ODSA/Books/CS3/html/index.html'>CS3 Data Structures & Algorithms</a> by OpenDSA</>,
    <><a href='https://goalkicker.com/AlgorithmsBook/'>Algorithms Notes for Professionals book</a> from goalkicker</>,
    <>ChatGPT</>,
    <div><a href='https://www.cse.iitd.ac.in/~srsarangi/archbooksoft.html'>Basic Computer Architecture</a> by Smruti R. Sarangi</div>,
    <><a href='https://www.elearningfrench.com'>elearningfrench.com</a></>,
    <><a href='https://www.optilingo.com/blog/french/french-pronouns/'>optilingo.com/blog/french/french-pronouns/</a></>,
    <>Madinah Arabic Book 2 from <a href='http://www.lqtoronto.com/madinaarabic.html'>lqtoronto</a></>,
    <div className="emailed">York University, AP/LING 3150 M (2023 Winter)</div>,
    <><a href='https://openstax.org/details/books/university-physics-volume-1'>University Physics (Vol 1)</a> from OpenStax</>,
    <><a href='https://openstax.org/details/books/university-physics-volume-3'>University Physics (Vol 3)</a> from OpenStax</>,
    <>Atmospheric Processes and Phenomena book, available <a href="https://pressbooks-dev.oer.hawaii.edu/atmo/">here</a></>,
    <>Physical Geogology book, available <a href="https://opentextbc.ca/geology/">here</a></>,
    <>Introduction to History and Philosophy of Science book, available <a href="http://hakobsandbox.openetext.utoronto.ca/">here</a></>,
    <div className="emailed">York University, LE/EECS 3482 M course (Winter 2023)</div>,
    <>York University, SC/MATH 4161 M course (Winter 2023)</>,
    <>MIT course 18.781 <a href='https://ocw.mit.edu/courses/18-781-theory-of-numbers-spring-2012/'>Theory Of Numbers</a> (Instructor: Prof. Abhinav Kumar)</>,
    <><a href='https://openstax.org/details/books/calculus-volume-1'>Calculus (Vol 1)</a> from OpenStax</>,
    <>York University, LE/EECS 4412 M course (Winter 2023)</>,
    <>An Introduction To R: <a href="https://cran.r-project.org/doc/manuals/r-release/R-intro.html">https://cran.r-project.org/doc/manuals/r-release/R-intro.html</a></>,
    <><a href='https://en.wikibooks.org/wiki/R_Programming'>R Programming</a> from WikiBooks</>,
    <><a href='https://ocw.mit.edu/courses/6-050j-information-and-entropy-spring-2008'>Information and Entropy (6.050J)</a> course from MIT</>,
    <><a href='https://mostlyharmlessstat.wixsite.com/webpage'>Mostly Harmless Statistics</a> by Rachel L. Webb</>,
    <><a href='https://www.lawlessfrench.com/products/progress-with-lawless-french/'>Progress with Lawless French</a></>,
    <>Wiktionary</>,
    <><a href='https://ecampusontario.pressbooks.pub/french/'>Introduction to French</a> by Rita Palacios</>,
    <><a href='https://dn720001.ca.archive.org/0/items/liberte-complete-july-2022/Liberte_Complete_July_2022.pdf'>Liberté</a> by Gretchen Angelo</>,
    <>French OER (1 - 4) (Carrasco, Zahedi, and Parrish), available <a href='https://human.libretexts.org/Bookshelves/Languages/French'>here</a></>,
    <>COMP 4300 Game Programming course (available <a href='https://www.youtube.com/watch?v=s99UDGdYIUE&list=PL_xRyXins84_Jf-aCh7chj47HR4oZLPwK'>here</a>)</>,
    <>Weiten, W., & McCann, D. (2016). <i>Psychology: Themes & Variations</i> (4th ed.). Nelson Education.</>,
    <>UML Diagrams Full Course <a href='https://www.youtube.com/watch?v=WnMQ8HlmeXc'>video</a> from freeCodeCamp.org</>,
    <div className="emailed">Source 1</div>,
    <>Source 2, whether a piece of content is from source 1 or 2 would be specified in the article, or you would have to use the colors.</>,
    <>Source 3, sometimes instead of mentioning the source name, colors would be used to identify the source.</>,
    <><a href='https://www.sfml-dev.org'>https://www.sfml-dev.org</a></>,
    <>Strayer, J. K. (2002). Elementary Number Theory.</>,
    <>Stillman, J. M. (1960). The story of alchemy and early chemistry (The Story of Early Chemistry).</>,
    <><a href='https://openstax.org/details/books/chemistry-2e'>Chemistry (2e)</a> by OpenStax</>,
    <><a href='https://www.google.ca/books/edition/Web_Based_Learning_through_Educational_I/hHoVhZ8cm88C?hl=en&gbpv=0'>Web-Based Learning through Education Informatics: Information Science Meet Educational Computing</a> by Nigel Ford</>,
    <><a href='https://udlbook.github.io/udlbook/'>Understanding Deep Learning</a></>,
    <><a href='https://www.dr-chuck.com/net-intro/'>Introduction to Networking: How the Internet Works</a></>,
    <><a href='https://pages.cs.wisc.edu/~remzi/OSTEP/'>Operating Systems: Three Easy Pieces</a> by Remzi H. Arpaci-Dusseau and Andrea C. Arpaci-Dusseau</>,
    <></>
]