truncate study_notes_backend_sources;

insert into study_notes_backend_sources values
(1,'{electrical_engineering}','<a href="https://eng.libretexts.org/Bookshelves/Electrical_Engineering/Signal_Processing_and_Modeling/Signals_and_Systems_(Baraniuk_et_al.)">Signals and Systems</a> (Baraniuk et al.)'),
(2,'{electrical_engineering}' ,'<a href="https://www.opentextbooks.org.hk/system/files/export/9/9648/pdf/Fundamentals_of_Electrical_Engineering_I_9648.pdf">Fundamentals of Electrical Engineering I</a> by Don H. Johnson'),
(3,'{electrical_engineering}', '<a href="https://en.wikibooks.org/wiki/Signals_and_Systems">Signals and Systems</a> from Wikibooks'),
(4,'{miscellaneous}', 'Random Wikipedia Articles'),
(5,'{mathematics}', '<a href="https://discrete.openmathbooks.org/dmoi4/dmoi4.html">Discrete Mathematics: 
An Open Introduction</a>, 4th Edition by Oscar Levin'),
(6,'{natural_sciences}', '<a href="https://openstax.org/details/books/university-physics-volume-2">University Physics (Vol 2)</a> from OpenStax'),
(7,'{statistics}', '<a href="https://openstax.org/details/books/introductory-statistics-2e">Introductory Statistics (2e)</a> from OpenStax'),
(8,'{computer_science_(advanced_topics)}', 'MIT 6.S191: <a href="http://introtodeeplearning.com/2023/index.html">Introduction to Deep Learning</a>, &copy; Alexander Amini and Ava Soleimany'),
(9,'{computer_science_(advanced_topics)}', '<a href="https://d2l.ai">d2l.ai</a> (Dive into Deep Learning)'),
(10,'{language_learning}', 'Youtube playlist: <a href="https://www.youtube.com/playlist?list=PLbFrQnW0BNMUkAFj4MjYauXBPtO3I9O_k">Billy Go"s Beginner Korean Course</a>'),
(11,'{language_learning}', 'koreanwikiproject.com'),
(12,'{language_learning}', 'Youtube Channel: <a href="https://www.youtube.com/@KOREANFULLCOURSE">KOREAN FULL COURSE</a>'),
(13,'{language_learning}', '<a href="https://www.90daykorean.com">90daykorean.com</a>'),
(14,'{computer_science_fundamentals}', '<a href="https://www.learncpp.com">learncpp.com</a>'), 
(15,'{computer_science_fundamentals}', '<a href="https://en.wikibooks.org/wiki/C_Programming">C Programming</a> from Wikibooks'),
(16,'{language_learning}', 'Doulingo'),
(17,'{language_learning}', 'http://www.lqtoronto.com/videos.html'),
(18,'{language_learning}', 'Madinah Arabic Book 3 from <a href="http://www.lqtoronto.com/madinaarabic.html">lqtoronto</a>'),
(19,'{art}','<a href="https://www.youtube.com/playlist?list=PLroLjS4HDi0BLMx3d7mzROMfm7bC9ZQuc">Color Theory</a> playlist by The Futur Academy'),
(20,'{computer_science_fundamentals}', '<a href="https://opendsa-server.cs.vt.edu/ODSA/Books/Everything/html/index.html">OpenDSA Data Structures and Algorithms Modules Collection</a> by OpenDSA'),
(21,'{art}','<a href="https://thepublicstudio.ca/files/DIY-No7-Colour.pdf">Introduction to Color</a> from The Public'),
(22, '{art}','<a href="https://rmit.pressbooks.pub/colourtheory1/">Colour Theory: Understanding and Working with Colour</a> by Lisa Cianci'),
(23,'{computer_science_fundamentals}', '<a href="https://www.cse.iitd.ac.in/~srsarangi/archbooksoft.html">Basic Computer Architecture</a> by Smruti R. Sarangi'),
(24,'{language_learning}', '<a href="https://www.elearningfrench.com">elearningfrench.com</a>'),
(25,'{language_learning}', '<a href="https://www.optilingo.com/blog/french/french-pronouns/">optilingo.com/blog/french/french-pronouns/</a>'),
(26,'{language_learning}', 'Madinah Arabic Book 2 from <a href="http://www.lqtoronto.com/madinaarabic.html">lqtoronto</a>'),
(27,'{language_learning}', '<div className="emailed">York University, AP/LING 3150 M (2023 Winter)</div>'),
(28,'{natural_sciences}', '<a href="https://openstax.org/details/books/university-physics-volume-1">University Physics (Vol 1)</a> from OpenStax'),
(29,'{natural_sciences}', '<a href="https://openstax.org/details/books/university-physics-volume-3">University Physics (Vol 3)</a> from OpenStax'),
(30,'{natural_sciences}', '<a href="https://pressbooks-dev.oer.hawaii.edu/atmo/">Atmospheric Processes and Phenomena</a> by Alison Nugent; David DeCou; Shintaro Russell; and Christina Karamperidou'),
(31,'{natural_sciences}', '<a href="https://opentextbc.ca/physicalgeology2ed/">Physical Geogology</a> (2nd Edition) by Steven Earle'),
(32,'{natural_sciences}', '<a href="https://ecampusontario.pressbooks.pub/introhps/">Introduction to History and Philosophy of Science</a> by Barseghyan, Hakob; Overgaard, Nicholas; and Rupik, Gregory'),
(33,'{computer_science_fundamentals}', '<div className="emailed">York University, LE/EECS 3482 M course (Winter 2023)</div>'),
(34,'{natural_sciences}', 'A Little History of Science by William Bynum'),
(35,'{mathematics}', 'MIT course 18.781 <a href="https://ocw.mit.edu/courses/18-781-theory-of-numbers-spring-2012/">Theory Of Numbers</a> (Instructor: Prof. Abhinav Kumar)'),
(36,'{mathematics}', '<a href="https://openstax.org/details/books/calculus-volume-1">Calculus (Vol 1)</a> from OpenStax'),
(37,'{computer_science_(advanced_topics)}', 'York University, LE/EECS 4412 M course (Winter 2023)'),
(38,'{computer_science_fundamentals}', 'An Introduction To R: <a href="https://cran.r-project.org/doc/manuals/r-release/R-intro.html">https://cran.r-project.org/doc/manuals/r-release/R-intro.html</a>'),
(39,'{computer_science_fundamentals}', '<a href="https://en.wikibooks.org/wiki/R_Programming">R Programming</a> from WikiBooks'),
(40,'{computer_science_fundamentals}', '<a href="https://ocw.mit.edu/courses/6-050j-information-and-entropy-spring-2008">Information and Entropy (6.050J)</a> course from MIT'),
(41,'{statistics}', '<a href="https://mostlyharmlessstat.wixsite.com/webpage">Mostly Harmless Statistics</a> by Rachel L. Webb'),
(42,'{language_learning}', '<a href="https://progress.lawlessfrench.com/revision">Progress with Lawless French</a>'), --remove later
(43,'{language_learning}', 'Wiktionary'),
(44,'{language_learning}', '<a href="https://ecampusontario.pressbooks.pub/introductiontofrench2nded/">Introduction to French (2nd ed.)</a> by Rita Palacios'),
(45,'{mathematics}', '<a href="https://openstax.org/details/books/calculus-volume-2">Calculus (Vol 2)</a> from OpenStax'),
(46,'{language_learning}', 'French OER (1 - 4) (Carrasco, Zahedi, and Parrish), available <a href="https://human.libretexts.org/Bookshelves/Languages/French">here</a>'),
(47,'{computer_science_fundamentals}', '<a href="https://learn.microsoft.com/en-us/cpp/cpp">C++ lessons</a> from Microsoft (Visual Studio 2022)'),
(48,'{miscellaneous}', 'Weiten, W., & McCann, D. (2016). <i>Psychology: Themes & Variations</i> (4th ed.). Nelson Education.'),
(49,'{computer_science_fundamentals}', 'UML Diagrams Full Course <a href="https://www.youtube.com/watch?v=WnMQ8HlmeXc">video</a> from freeCodeCamp.org'),
(50,'{miscellaneous}', '<div className="emailed">Source 1</div>'),
(51,'{miscellaneous}', 'Source 2, whether a piece of content is from source 1 or 2 would be specified in the article, or you would have to use the colors.'),
(52,'{miscellaneous}', 'Source 3, sometimes instead of mentioning the source name, colors would be used to identify the source.'),
(53,'{computer_science_fundamentals}', '<a href="https://docs.manim.community/en/stable/index.html">Manim community Website</a> (although some examples are my own)'),
(54,'{mathematics}', 'Strayer, J. K. (2002). Elementary Number Theory.'),
(55,'{natural_sciences}', 'Stillman, J. M. (1960). The story of alchemy and early chemistry (The Story of Early Chemistry).'),
(56,'{natural_sciences}', '<a href="https://openstax.org/details/books/chemistry-2e">Chemistry (2e)</a> from OpenStax'),
(57,'{miscellaneous}', '<a href="https://www.google.ca/books/edition/Web_Based_Learning_through_Educational_I/hHoVhZ8cm88C?hl=en&gbpv=0">Web-Based Learning through Education Informatics: Information Science Meet Educational Computing</a> by Nigel Ford'),
(58,'{computer_science_(advanced_topics)}', '<a href="https://udlbook.github.io/udlbook/">Understanding Deep Learning</a> by Simon J. D Prince'),
(59,'{computer_science_fundamentals}', '<a href="https://www.dr-chuck.com/net-intro/">Introduction to Networking: How the Internet Works</a>'),
(60,'{computer_science_fundamentals}', '<a href="https://pages.cs.wisc.edu/~remzi/OSTEP/">Operating Systems: Three Easy Pieces</a> by Remzi H. Arpaci-Dusseau and Andrea C. Arpaci-Dusseau'),
(61,'{computer_science_(advanced_topics)}', '<a href="https://joyofcryptography.com">The Joy of Cryptography</a> by Mike Rosulek'),
(62,'{computer_science_fundamentals}', 'MIT course <a href="https://ocw.mit.edu/courses/6-s095-programming-for-the-puzzled-january-iap-2018/pages/syllabus/">6.S095</a>'),
(63,'{computer_science_(advanced_topics)}', '<a href="http://www.stat.ucla.edu/~ywu/linear.pdf">The mathematics of quantum mechanics</a>, Martin Laforest'),
(64,'{computer_science_fundamentals}', '<a href="https://www.mclibre.org/descargar/docs/revistas/magpi-books/raspberry-pi-c-gui-programming-en-201904.pdf">An Introduction to C & GUI Programming</a> by Simon Long'),
(65,'{mathematics}', '<a href="https://openstax.org/details/books/calculus-volume-3">Calculus (Vol 3)</a> from OpenStax'),
(66,'{mathematics}', 'Rosen, Kenneth H. (2000). Elemtary Number Theory and Its Applications.'),
(67, '{mathematics}','<a href="http://linear.ups.edu/html/fcla.html">A First Course in Linear Algebra</a> by Robert A. Beezer'),
(68, '{computer_science_fundamentals}', 'PostgreSQL basics: <a href="https://neon.tech/postgresql/postgresql-getting-started">https://neon.tech/postgresql/postgresql-getting-started</a>'),
(69, '{computer_science_fundamentals}', 'Data Mining and Business Analytics with R by Johannes Ledolter'),
(70, '{computer_science_fundamentals}', '<a href="https://scholarworks.montana.edu/items/8d0ebbc9-147f-498b-8c9f-f1735d8e74cf">Intermediate Statistics with R</a> by Greenwood, Mark C.'),
(71, '{language_learning}', '<a href="https://www.howtostudykorean.com/">howtostudykorean.com</a>'),
(72, '{language_learning}', '<a href="https://www.verbix.com/languages/korean">Korean verb conjugator</a>'),

(74, '{language_learning}', '<a href="https://www.renshuu.org">Renshuu</a>'),
(75, '{language_learning}', '<a href="https://progress.lawlessfrench.com/learn/theme">Vocabulary Lists</a> by Progress with Lawless French.'),
(76, '{computer_science_(advanced_topics)}', '<a href="https://www.microsoft.com/en-us/research/uploads/prod/2006/01/Bishop-Pattern-Recognition-and-Machine-Learning-2006.pdf">Pattern Recognition and Machine Learning</a> by Christopher M. Bishop'),
(77,'{electrical_engineering}','<a href="https://www.ece.uvic.ca/~frodo/sigsysbook/downloads/signals_and_systems-5.0.pdf">Signals and Systems</a> (Michael D. Adams)')
;