import { MathStuff } from "../../articleRelatedStuff/MathStuff"; 
import SubList from "../../articleRelatedStuff/SubList";
import { ImgComp } from "../../articleRelatedStuff/ImgComp";

export default function ConicSectionAndQuadraticSurfaces(){
  return <>
	  <h2>Conic Sections and Quadratic Surfaces</h2>
    <div className="content">
		<ul data-source={65} style={{width:" 49%",marginLeft: "0.5%",float: "left"}}>
			<li>Conic sections:<SubList>
				<li>A cone has two identically shaped parts called <b>nappes</b>. A right circular cone can be generated by revolving a line passing through the origin around the y-axis as shown.</li>
				<ImgComp src={"/articlePics/conic_section_and_quadratic_surfaces_pics/19.jfif"} width="50%" />
				<li><b>Conic sections</b> are generated by the intersection of a plane with a cone.</li>
				<li>If the plane intersects both nappes, then the conic section is a <b>hyperbola</b>.</li>
				<li>If the plane is parallel to the generating line, the conic section is a <b>parabola</b>.</li>
				<li>If the plane is perpendicular to the axis of revolution, the conic section is a <b>circle</b>.</li>
				<li>If the plane intersects one nappe at an angle to the axis (other than 90°), then the conic section is an <b>ellipse</b>.</li>
				<ImgComp src={"/articlePics/conic_section_and_quadratic_surfaces_pics/7.jfif"} width="90%" />
				<li><a href='https://en.wikipedia.org/wiki/Conic_section'>One property that defines a non-circular conic to be the set of those points whose distances to some particular point, called a <b>focus</b>, and some particular line, called a <b>directrix</b>, are in a fixed ratio, called the <b>eccentricity</b>.</a></li>
			</SubList></li>
			<li>Parabola:<SubList>
				<li>A <b>parabola</b> is the set of all points whose distance from a fixed point, called the <b>focus</b>, is equal to the distance from a fixed line, called the <b>directrix</b>. The point halfway between the focus and the directrix is called the <b>vertex</b> of the parabola.</li>
				<ImgComp src={"/articlePics/conic_section_and_quadratic_surfaces_pics/28.jfif"} width="90%" />
				<li>Given a parabola opening upward with vertex located at \((h,k)\) and focus located at \((h,k+p)\), where \(p\) is a constant, the <b>standard form</b> equation for the parabola is given by:</li>
				<MathStuff>$$ y = {"\\frac{(x-h)^2}{4p} + k"} $$</MathStuff>
				<li>The axis of symmetry of a vertical (opening up or down) parabola is a vertical line passing through the vertex.</li>
				<li>The parabola has an interesting reflective property. Suppose we have a satellite dish with a parabolic cross section. If a beam of electromagnetic waves, such as light or radio waves, comes into the dish in a straight line from a satellite (parallel to the axis of symmetry), then the waves reflect off the dish and collect at the focus of the parabola as shown.</li>
				<li>The general form of a parabola that opens either up or down is written as: \(ax^2 +bx+cy+d=0\).</li>
				<li>The general form of a parabola that opens either to the left or to the right is written as: \(ay^2 +bx+cy+d=0\).</li>
			</SubList></li>
			<li>Ellipses:<SubList>
				<li>An <b>ellipse</b> is the set of all points for which the sum of their distances from two fixed points (the <b>foci</b>) is constant.</li>
				<ImgComp src={"/articlePics/conic_section_and_quadratic_surfaces_pics/29.jfif"} />
				<li>The points \(P\) and \(P'\) are located at the ends of the <b>major axis</b> of the ellipse, and have coordinates \((a,0)\) and \((-a,0)\), respectively. The major axis is always the longest distance across the ellipse, and can be horizontal or vertical. Thus, the length of the major axis in this ellipse is \(2a\).</li>
				<li>The points \(Q\) and \(Q'\) are located at the ends of the minor axis of the ellipse, and have coordinates \((0,b)\) and \((0,-b)\), respectively. The <b>minor axis</b> is the shortest distance across the ellipse. The minor axis is perpendicular to the major axis.</li>
				<li>Consider the ellipse with center \((h,k)\), a horizontal major axis with length \(2a\), and a vertical minor axis with length \(2b\). Then the equation of this ellipse in standard form is:</li>
				<MathStuff>$$ {"\\frac{(x-h)^2}{a^2} + \\frac{(y-k)^2}{b^2}"} = 1$$</MathStuff>
				<li>The foci are located at \((h±c,k)\), where \(c^2 = a^2 - b^2\) and the equations of the directrices are \(x=h± \frac{"{a^2}{c}"}\).</li>
				<li>If the major axis is vertical, then the equation of the ellipse becomes</li>
				<MathStuff>$$ {"\\frac{(x-h)^2}{b^2} + \\frac{(y-k)^2}{a^2}"} = 1$$</MathStuff>
				<li>The foci are located at \((h,k±c)\), where \(c^2 = b^2 - a^2\) and the equations of the directrices are \(y=k± \frac{"{a^2}{c}"}\).</li>
				<li>The equation of an ellipse is in general form if it is in the form \(Ax^2 + By^2 + Cx+Dy+E=0\), where \(A\) and \(B\) are either both positive or both negative.</li>
			</SubList></li>
			<li>Hyperbola:<SubList>
				<li>A <b>hyperbola</b> is the set of all points where the difference between their distances from two fixed points (the foci) is constant.</li>
				<ImgComp src={"/articlePics/conic_section_and_quadratic_surfaces_pics/30.jfif"} width="70%" />
				<li>If the major axis (transverse axis) is horizontal, then the hyperbola is called <b>horizontal</b>, and if the major axis is vertical then the hyperbola is called <b>vertical</b>.</li>
				<li>Consider a horizontal hyperbola with center \((h,k)\). Then the equation of this ellipse is:</li>
				<MathStuff>$$ {"\\frac{(x-h)^2}{a^2} - \\frac{(y-k)^2}{b^2} = 1"} $$</MathStuff>
				<li>The foci are located at \((h±c,k)\), where \(c^2=a^2+b^2\). The equations of the asymptotes are given by \(y=k±{"\\frac{b}{a}"}(x-h)\). The equations of the directrices are:</li>
				<MathStuff>$$ {"x = h ±\\frac{a^2}{c}"} $$</MathStuff>
				<li>If the major axis is vertical, then the equation of the hyperbola becomes:</li>
				<MathStuff>$$ {"\\frac{\\frac{(y-k)^2}{a^2} - (x-h)^2}{b^2} = 1"} $$</MathStuff>
				<li>The foci are located at \((h,k±c)\), where \(c^2=a^2+b^2\). The equations of the asymptotes are given by \(y=k±{"\\frac{a}{b}"}(x-h)\). The equations of the directrices are:</li>
				<MathStuff>$$ {"y = k ±\\frac{a^2}{c}"} $$</MathStuff>
				<li>The equation of a hyperbola is in general form if it is in the form \(Ax^2+By^2+Cx+Dy+E=0\), where \(A\) and \(B\) have opposite signs.</li>
				<li>A ray directed toward one focus of a hyperbola is reflected by a hyperbolic mirror toward the other focus.</li>
			</SubList></li>
			<li>Eccentricity and directrix:<SubList>
				<li>The <b>eccentricity</b> \(e\) of a conic section is defined to be the distance from any point on the conic section to its focus, divided by the perpendicular distance from that point to the nearest directrix. This value is constant for any conic section, and can define the conic section as well.</li>
				<li>If \(e=1\), the conic is a parabola.</li>
				<li>If \(e \lt 1\), it is an ellipse.</li>
				<li>If \(e \gt 1\), it is a hyperbola.</li>
				<li>The eccentricity of a circle is zero.</li>
				<li>The directrix of a conic section is the line that, together with the point known as the focus, serves to define a conic section.</li>
				<li>Hyperbolas and noncircular ellipses have two foci and two associated directrices. Parabolas have one focus and one directrix.</li>
				<li>The equations of the directrices of a horizontal ellipse and a horizontal hperbola are \(x=± \frac{"{a^2}{c}"}\).</li>
			</SubList></li>
			<li>Polar equations of conic sections:<SubList>
				<li>The <b>focal parameter</b> of a conic section \(p\) is defined as the distance from a focus to the nearest directrix.</li>
				<li>The polar equation of a conic section with focal parameter \(p\) is given by:</li>
				<MathStuff>$$ {"{r= \\frac{ep}{1±e \\cos θ} \\text{ or } r= \\frac{ep}{1±e \\sinθ} }"} $$</MathStuff>
			</SubList></li>
			<li>General equations of degree two for conic sections:<SubList>
				<li>A general equation of degree two can be written in the form \(Ax^2+Bxy+Cy^2+Dx+Ey+F=0\). The graph of an equation of this form is a conic section. If \(B≠0\) then the coordinate axes are rotated.</li>
				<li>To identify the conic section, we use the discriminant of the conic section \(4AC-B^2\). One of the following cases must be true:<SubList opened>
					<li>\(4AC-B^2 \gt 0\): the graph is an ellipse.</li>
					<li>\(4AC-B^2=0\): the graph is a parabola.</li>
					<li>\(4AC-B^2 \lt 0\): the graph is a hyperbola.</li>
				</SubList></li>
				<li>The method for graphing a conic section with rotated axes involves determining the coefficients of the conic in the rotated coordinate system. The new coefficients are labeled \(A'\), \(B'\), \(C'\), \(D'\), \(E'\) and \(F'\), and are given by the formulas:</li>
				<MathStuff>$$ {"\\begin{align} A' &= A \\cos^2 θ+ B \\cos θ \\sin θ + C \\sin^2 θ \\\\ B' &= 0 \\\\ C' &= A \\sin^2 θ-B \\sin θ \\cos θ + C cos^2 θ \\\\ D' &= D \\cos θ + E \\sin θ \\\\ E' &= - D \\sin θ + E \\cos θ \\\\ F' &= F \\end{align}"} $$</MathStuff>
				<li>The procedure for graphing a rotated conic is the following:<SubList opened>
					<li>Identify the conic section using the discriminant  \(4AC-B^2\)</li>
					<li>Determine \(θ\) using the formula \(\cot (2θ) = \frac{"{A-C}{B}"}\)</li>
					<li>Calculate \(A'\), \(B'\), \(C'\), \(D'\), \(E'\) and \(F'\)</li>
					<li>Rewrite the original equation using  \(A'\), \(B'\), \(C'\), \(D'\), \(E'\) and \(F'\)</li>
					<li>Draw a graph using the rotated equation</li>
				</SubList></li>
			</SubList></li>
		</ul>
		<ul data-source={45} style={{width:" 49%",marginRight: "0.5%",float: "right"}}>
			<li><b>Cylinders:</b><SubList>
				<li>A set of lines parallel to a given line passing through a given curve is known as a cylindrical surface, or <b>cylinder</b>. The parallel lines are called <b>rulings</b>.</li>
				<figure>
					<ImgComp src={"/articlePics/conic_section_and_quadratic_surfaces_pics/1.jpeg"} width="60%"/>
					<figcaption>In three-dimensional space, the graph of equation \(z=x^3\) is a cylinder, or a cylindrical surface with rulings parallel to the \(y\)-axis.</figcaption>
				</figure>
				<li>The <b>traces</b> of a surface are the cross-sections created when the surface intersects a plane parallel to one of the coordinate planes.</li>
				<figure>
					<ImgComp src={"/articlePics/conic_section_and_quadratic_surfaces_pics/2.jpeg"} width="90%"/>
					<figcaption>(a) This is one view of the graph of equation \(z=\sin(x)\). (b) To find the trace of the graph in the \(xz\)-plane, set \(y=0\). The trace is simply a two-dimensional sine wave.</figcaption>
				</figure>
			</SubList></li>
			<li><b>Quadric Surfaces:</b><SubList>
				<li>Quadric surfaces are the graphs of equations that can be expressed in the form:</li>
				<MathStuff>\[\begin{"{gather}"} Ax^2+By^2+Cz^2+Dxy+Exz+ \\ Fyz+Gx+Hy+Jz+K=0 \end{"{gather}"} \]</MathStuff>
				<li>When a quadric surface intersects a coordinate plane, the trace is a conic section.</li>
				<li>An <b>ellipsoid</b> is a surface described by an equation of the form:</li>
				<MathStuff>\[{"\\frac{x^2}{a^2}+\\frac{y^2}{b^2}+\\frac{z^2}{c^2}=1"} \]</MathStuff>
				<li>The trace of an ellipsoid is an ellipse in each of the coordinate planes.</li>
				<li><b>Elliptic paraboloid:</b></li>
				<MathStuff>\[{"\\frac{x^2}{a^2}+\\frac{y^2}{b^2}=\\frac{z}{c}"} \]</MathStuff>
				<li>The trace in the \(xy\)-plane is an ellipse, but the traces in the \(xz\)-plane and \(yz\)-plane are parabolas.</li>
			</SubList></li>
			<li>Common quadratic sufaces:<SubList>
				<ImgComp src={"/articlePics/conic_section_and_quadratic_surfaces_pics/3.jpeg"} width="100%"/>
				<ImgComp src={"/articlePics/conic_section_and_quadratic_surfaces_pics/4.jpeg"} width="100%"/>
			</SubList></li>
		</ul>
		</div>
  </>;
}